main/features/org.talend.top.feature/feature.xml
main/plugins/org.talend.rcp.branding.top/META-INF/MANIFEST.MF
main/plugins/org.talend.rcp.branding.top/plugin.xml

https://jira.talendforge.org/browse/TUP-2649
Rename plugin name, since the old plugin name can not be loaded into tis

TUP-2649 new feature: Update branding plugins to use Talend Theme

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/CorePlugin.java

not store the columns on branch 6.2

bug fixed TDQ-13229 restart TOS_DQ studio, then re-create analysis, can

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/OpenItemEditorAction.java

TDQ-13238 Remove code of reloading property,reload repositoryViewObject

---

main/plugins/org.talend.dataprofiler.core/plugin.xml
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/CorePlugin.java

TDQ-11348 the import button should be disabled when the user is read

---

main/plugins/org.talend.dataquality.sampling/pom_dq.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.0]

---

main/libraries/pom.xml
main/plugins/org.talend.dataquality.common/README.md
main/plugins/org.talend.dataquality.record.linkage/README.md
main/plugins/org.talend.dataquality.sampling/README.md
main/plugins/org.talend.dataquality.standardization/README.md
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1]

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBConnectionRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/factory/DQRepNodeCreateFactory.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/OpenItemEditorAction.java

bug fixed TDQ-13634 catch exception when there are some connection file

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/AbstractAnalysisMetadataPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/ColumnAnalysisDetailsPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/ColumnSetAnalysisDetailsPage.java

with sample data" get unexpected dialog pop up, can't checked.

bug fixed TDQ-13704 when java analysis add java indicators, check "Run

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnAnalysisSqlExecutor.java

TDQ-13909: fix profiling run Hive on Spark error by not support its

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/RecycleBinRepNode.java

TDQ-13982 only display "connections" "hadoop" "fileDelimited" folders

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/ReportAnalysisRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/ReportSubFolderRepNode.java

TDQ-14128 Replace 'RepositoryObject' with RepositoryViewObject and code

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/adapter/AnalysisMatchParameterAdapter.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/MatchAnalysisDetailsPage.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/composite/ParticularDefaultSurvivorshipTableComposite.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/composite/tableviewer/AbstractMatchAnalysisTableViewer.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/composite/tableviewer/ParticularDefaultSurvivorShipCellModifier.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/composite/tableviewer/ParticularDefaultSurvivorShipTableViewer.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/composite/tableviewer/editingSupport/FunctionEditingSupport.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/composite/tableviewer/provider/ParticularDefaultSurvivorshipLabelProvider.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/section/SelectAlgorithmSection.java
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/section/definition/ParticularDefSurshipDefinitionSection.java

TDQ-14135 modify match analysis editor to support Default survivorship

---

main/features/org.talend.top.feature/feature.xml

feat(TUP-18351):Implement the search/deploy/update snapshot for nexus

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriter.java

bug fixed TPS-2154 handle IndexOutOfBoundsException happen after

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriter.java

bug fixed TDQ-14269 IndexOutOfBoundsException happen after migrated to

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/DelimitedFileSQLExecutor.java

TDQ-14373: fix the "Limit" in analysis editor doesn't work for csv mode

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/dialog/MatchRuleElementTreeSelectionDialog.java

bug fixed TDQ-14378 Fixed NPE on tRecordMatching and show error on

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/DelimitedFileSQLExecutor.java

TDQ-14449: fix lost one line data when file connection use csv mode and

---

main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/DatePatternFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/MaxValueIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/MinValueIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/PatternFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/PatternLowFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/RangeIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/ValueIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/mapdb/TalendFormatDate.java

1. min and max indicator show the correct result;
2.Low/PatternFrequency indicator show correct result;
3.Low/PatternFrequency  and DatePatternFrequency indicators can drill
down.

TDQ-14385 for Date type on DelimitedFile connection:

---

main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/action/RemoveMatchKeyDefinitionAction.java

Reverts Talend/tdq-studio-se#183

Revert "TDQ-14465: fix "Delete" in Survivorship Rules for Columns did not work"

---

main/plugins/org.talend.dataquality.record.linkage.ui/src/messages.properties
main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/section/MatchingKeySection.java

TDQ-14343: add a warning message when no Match function was added for

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/CorePlugin.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/ExportWizardPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/action/ExportItemAction.java

* Export wizard should show the same order with repository tree
* Make "export" in toolbar the same with behavior right-click menu
* Align other behavior with DI perspective

fix(TDQ-14573): improve the export dialog

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/AnalysisRecordGroupingUtils.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/match/ExecuteMatchRuleHandler.java

and tMatchGroup
- add method and parameter to support it
- add junit

feat TDQ-14276 support "most recent" and "most ancient" in matchAnalysis

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/ImportMatchRuleAction.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/dialog/MatchRuleElementTreeSelectionDialog.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/MatchAnalysisDetailsPage.java

Rules For Columns" in match analysis
- add check when importing rules 
- add check when saving analysis

fix TDQ-14696 Should not exist the dupplicate columns for "survivorship

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/ConnectionUtils.java

TDQ-14773 Use data type String to judge the JDBC connection so as to

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/ConnectionUtils.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/CWMPlugin.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/RepositoryNodeHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/service/TOPDriverService.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/AbstractMetadataCreationAction.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/OpenItemEditorAction.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/provider/DuplicateResourceProvider.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/views/provider/DQRepositoryViewLabelProvider.java

display the icon in recyle bin
lock the node when open it
make tdqReportRun work
add duplicate

feat(TDQ-14786): support hybrid tcomp/database

---

main/plugins/org.talend.dataprofiler.rcp/src/org/talend/dataprofiler/rcp/intro/ApplicationActionBarAdvisor.java

bug: TDQ-14801 The "Boot a new Talend open studio." should not shown for

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/RepositoryNodeHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/ExportWizardPage.java

- when using exchange and export, need to check null

bug TDQ-14848 NPE when click 'Export' button and slow

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/ZipFileImportWriter.java

fix(TDQ-14949): fix cannot import the items when the source path like

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/AnalysisRecordGroupingUtils.java

- caused by pattern from file connection ""xxxxx""

fix TDQ-14964 "most recent" not correct for file connection

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/database/ColumnFilterWizard.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/database/ColumnFilterWizardPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/database/MetaDataFilterWizard.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/database/MetaDataFilterWizardPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/database/TableViewFilterWizard.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/database/TableViewFilterWizardPage.java

fix     TDQ-14861 UI not rendering well for metadata connection filter

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/service/TOPRepositoryService.java

fix(TDQ-14841): SqlExplorer support the connection which has empty

---

main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/AverageLengthIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/AvgLengthWithBlankIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/AvgLengthWithBlankNullIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/AvgLengthWithNullIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/DefValueCountIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/FrequencyIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/MaxLengthIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/MinLengthIndicatorImpl.java

TDQ-14961 Support surrogate pair in all indicators when compute String

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/provider/OverViewAnalysisActionProvider.java

-check different DB or different type will not show

fix     TDQ-8555 "overview analysis" on the right click menu

---

main/plugins/org.talend.dataquality.record.linkage.ui/src/org/talend/dataquality/record/linkage/ui/section/MatchingKeySection.java

* fix(TDQ-14852): Remove the fix height on tab item
* fix(TDQ-14852): fixed on linux OS

fix(TDQ-14852): Remove the fix height on tab item (#252)

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/EMainNodesTreeType.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/RepositoryNodeComparator.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ImageLib.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/CreateDFConnectionAction.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/DQCreateContextAction.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/ExportWizardPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/ItemRecord.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/utils/ComparatorsFactory.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/views/provider/ResourceViewContentProvider.java

fix(TDQ-15009): the order of Repository Tree in the export wizard should be same with studio

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/OpenItemEditorAction.java

fix(TDQ-14934): fix can use the studio associate application to open

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/ConnectionUtils.java

call UI plugin when run tdqReportRun

bugfix(TDQ-15259) Don't check the real jdbc jar path so that avoid to

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/views/provider/DQRepositoryViewLabelProvider.java

- when dbconnection editor open, on its table view nodes should not show
lock icon.

fix     TDQ-15425

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/CompositeIndicator.java

fix     TDQ-15543 the order of indicators in analysis result always

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/DelimitedFileSQLExecutor.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/file/FileCSVReader.java

connection on DQ top build of 711M1

fix TDQ-15502 Error occured when run match analysis with CSV file

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/migration/helper/IndicatorDefinitionFileHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/ExportWizardPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/ItemRecord.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/migration/helper/IndicatorDefinitionFileHelperTest.java

CI/CS_Word_Pattern_(Low_)Frequency

fix(TDQ-15555): fix NPE and ignore to export

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnAnalysisSqlExecutor.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/IndicatorUnit.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/model/states/utils/FrequencyTypeStateUtil.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/filters/SpecialLimitFrequencyAnalysisFilter.java

fix(TDQ-15362): Fix the number of show on the result for Benford Law

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/RepositoryNodeHelper.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/AnalysisFolderRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/ReportFolderRepNode.java

fix TDQ-15309 count number disappear which following "Analyses" and

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/resourcehelper/ContextResourceFileHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/ExportWizardPage.java

can not check context directly.

fix(TDQ-15354): export report which use context get from Preference page

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/DatabaseSQLExecutor.java

TDQ-15606 Replace 'Limit' with  'statement.setMaxRows(limit)' for jdbc

---

main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/FrequencyIndicatorImpl.java
test/plugins/org.talend.dataquality.test/src/org/talend/dataquality/indicators/impl/PatternFreqIndicatorImplTest.java

fix(TDQ-15573): fix the East Asia pattern indicators show well for

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnAnalysisSqlExecutor.java

fix TDQ-15995 benford law indicator result is not correct for invalid

---

main/plugins/org.talend.dataprofiler.core/src/messages.properties
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriter.java

Add error message when pattern is builtin mode

fix(TDQ-16007) Can't import analysis because db connection is used Part II

---

test/plugins/org.talend.dataprofiler.core.test/src/org/talend/AllDataProfilerCoreTests.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriterTest.java

fix(TDQ-16024): disable junit test case for FileSystemImportWriterTest.

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/dbms/MSSqlDbmsLanguage.java

generated job doesn't quote the column names table names
- add quote \" in method getHardCodedQuoteIdentifier

fix      TDQ-15741 query in Business Rule analysis based on mssql

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/model/states/freq/FrequencyTypeStates.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/model/states/table/FrequencyTableState.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/model/states/utils/FrequencyTypeStateUtil.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/utils/DrillDownUtils.java

- give a bigger value to show the result in the table

fix     TDQ-15967 CS Word pattern can not be listed

---

test/plugins/org.talend.cwm.management.test/src/org/talend/dq/helper/AnalysisExecutorHelperTest.java

fix(TDQ-16079): fixed failed junit test cases. Remove builtIn mode for

---

main/plugins/org.talend.dataprofiler.core/cheatsheets/DBconnection_cheat.xml
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/views/provider/DQRepositoryViewLabelProvider.java

chore(TDQ-15727): fix The icon for reference project is not consistent

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/ImportWizard.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriter.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/ZipFileImportWriter.java

* fix(TDQ-15946): always clean the temp folder
* fix(TDQ-15946): when import, unzip a temp folder with a new unique name to avoid the duplicated folder

Msjian/tdq 15946 import fucntions (#358)

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/ContextHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/helper/ContextViewHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/AbstractMetadataFormPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/AbstractAnalysisMetadataPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/composite/ContextComposite.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriter.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/views/context/TdqContextViewComposite.java

-when rename context parameter, related field in analysis need to be
updated
- when imported items didnot contains used context, make it buildin

item     TDQ-15353 Rename variable issue for Repository context

---

main/plugins/org.talend.dataprofiler.rcp/plugin.xml

fix(TDQ-15991)Add extenstion 'libraryNeeded' for some missing jars on

---

main/features/org.talend.top.libraries.feature/feature.xml

Fix : TUP-21137 Security: jtds-1.3.1-patch.jar ntlmauth loaded from a path variable
https://jira.talendforge.org/browse/TUP-21137

Fix : TUP-21137 Security: jtds-1.3.1-patch.jar ntlmauth loaded from a

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/ImportWizardPage.java

chore(TDQ-16108): Make sure Finish button work well when import analysis

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/model/states/table/FrequencyTableState.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CIWordPatternFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CIWordPatternLowFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CSWordPatternFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CSWordPatternLowFreqIndicatorImpl.java

fix(TDQ-15994): make the resutl show normal for frenquency percent on

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/preview/model/states/table/FrequencyTableState.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CIWordPatternFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CIWordPatternLowFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CSWordPatternFreqIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/CSWordPatternLowFreqIndicatorImpl.java

fix(TDQ-15994): make the resutl show normal for frenquency percent on analysis result page

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/ContextHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/helper/ContextViewHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/service/TOPRepositoryService.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriter.java

TDQ-16114 Action not correct when Rename variable but select NO option
- change the parameter in update context method
- change logic for selecting NO

Item    TDQ-15353 Rename variable issue for Repository context

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/indicators/AbstractSchemaEvaluator.java

analyzed mssql connection is context mode, schema overview analysis in
tDqReportRun job can not run.

Fix     TDQ-16068

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/views/resources/LocalRepositoryObjectCRUD.java

project to folder of reference project

Fix     TDQ-15167 There is a exception when we Drag node from main

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/migration/impl/CheckAndUpdateAnalysisDependencyTask.java

Fix TUP-21305 Set the secure processing feature on TransformerFactory instances
https://jira.talendforge.org/browse/TUP-21305

Fix TUP-21305 Set the secure processing feature on TransformerFactory instances

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/AnalysisHandler.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/TableAnalysisHandler.java

and result page can not be switched.
- donot show the same catalog/schema

Fix     TDQ-9247 During running a table analysis, between its setting

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/DQDeleteAction.java

GIT mode
https://jira.talendforge.org/browse/TUP-19978

fix(TUP-19978)It is very slow to delete many items at the same time on

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/AbstactSchemaAnalysisExecutor.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/AbstractFilterMetadataPage.java

parameter "Filter on tables" and "Filter on views"

Feature     TDQ-16326 in overview analysis, support context in the

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/helper/ContextViewHelper.java

Feat     TDQ-16235 Update related ana/report when adding/delete context

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/RepositoryNodeHelper.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/dialog/MetadataAndColumnSelectionDialog.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/analysis/AbstractAnalysisWizardPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/wizard/analysis/AnalysisDPSelectionPage.java

The match analysis can not used the db which is from reference project
when the merge button is unchecked

Fix TDQ-16363

---

main/plugins/net.sourceforge.sqlexplorer/src/net/sourceforge/sqlexplorer/dataset/DataSet.java

Fix     TDQ-16413 preview table which has bigint unsigned columns(value

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnAnalysisSqlExecutor.java

date with the indicators Pattern Low Frequency

Fix     TDQ-16514 basic analysis run failed when analysis Time_Stamp

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/migration/impl/CheckAndUpdateAnalysisDependencyTask.java

+ disallow doctypes for DocumentBuilderFactory instances

Fix     TDQ-16432 Enable secure processing

---

main/plugins/net.sourceforge.sqlexplorer/src/net/sourceforge/sqlexplorer/plugin/editors/SQLEditor.java

source file editor, get NPE in error log.

Fix    TDQ-15236 [Studio] Upgrade to Eclipse 4.10.x: TDQ-16727 close

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/indicator/UDIMasterPage.java

cause ui can not show correctly.

Fix TDQ-16737 new created udi change definition from java to others

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnAnalysisSqlExecutor.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/explore/ColumnDependencyExplorer.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/explore/FunctionFrequencyStatExplorer.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/explore/RowMatchExplorer.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/dbms/BigQueryDbmsLanguage.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/dbms/DbmsLanguage.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/dbms/DbmsLanguageFactory.java
main/plugins/org.talend.dataprofiler.core/indicators/Fraud Detection/Benford Law Frequency.definition
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/migration/impl/AddBenfordLawPattern4BigQueryTask.java

Preview column;
drilldown for FunctionalDependency;
Pattern (Low) Frequency;
Benford Law for int64;

feat(TDQ-15039): fix bigquery errors as follows:

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/dqrules/ParserRuleMasterDetailsPage.java

- remove the test rule button in the parser rule page

Fix     TDQ-16726 NPE error pop up when open the editor by double click the created rule

---

test/plugins/org.talend.cwm.management.test/src/org/talend/cwm/management/api/SoftwareSystemManagerTest.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/analysis/connpool/TdqAnalysisConnectionPoolTest.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/helper/EObjectHelperTest.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/helper/ProxyRepositoryManagerTest.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/helper/RepositoryNodeHelperTest.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/indicators/AbstractSchemaEvaluatorTest.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/indicators/ColumnSetIndicatorEvaluatorTest.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/indicators/DelimitedFileIndicatorEvaluatorTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/CorePluginTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/helper/WorkspaceResourceHelperTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/service/TDQResourceChangeHandlerTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/service/TOPRepositoryServiceTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/action/actions/ImportObjectTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/action/actions/handle/AnalysisHandleTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/editor/preview/model/ChartTableFactoryTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/imex/model/FileSystemImportWriterTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/utils/ModelElementIndicatorRuleTest.java
test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/utils/RepNodeUtilsTest.java

This reverts commit d431d58ac23a4ebfa360fc02d2f01473ffb83390.

Revert "Kwang/tup 22672 upgrade jars for powermock (#505)"

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/dbms/DbmsLanguageFactory.java

fix(TDQ-16952) NPE error occurred when Generate an ELT job from DQ Rule

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/migration/impl/EncryptAndDecryptPasswordTask.java

kjwang/Fix TUP-21205 Remove CryptoHelper
https://jira.talendforge.org/browse/TUP-21205

kjwang/Fix TUP-21205 Remove CryptoHelper

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/TableAnalysisSqlExecutor.java

fix(TDQ-14843): fix Business rule analysis select several tables will

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/helper/ContextViewHelper.java

to all the analysis and report in the repository.

Fix     TDQ-17107 add context for db used context, this context will add

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/composite/AnalysisColumnNominalIntervalTreeViewer.java

fix(TDQ-3984): fix column correlation analysis is not available on file

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/helper/ContextViewHelper.java

Fix     TDQ-17169 analysis/report will add built-in parameters when add

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/indicator/UDIMasterPage.java

Refresh composite when needed
sql and java udi can be added in an UDI editor

fix(TDQ-10826) fix some UI operation problems:

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/dialog/MatchRuleElementTreeSelectionDialog.java

fix(TDQ-17061): Make sure most trusted source valid for all the data

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/db/connection/DatabaseSQLExecutor.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/AnalysisExecutor.java

connection not set db parameter

fix(TDQ-17324): fix analysis can not run specially when snowflake

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/AnalysisExecutorSelector.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnAnalysisExecutor.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnSetAnalysisExecutorWithSampleData.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/TableAnalysisSqlExecutor.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/indicators/ColumnSetIndicatorEvaluator.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/indicators/ColumnSetIndicatorEvaluatorWithSampleData.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/helpers/AnalysisHelper.java

sample data" still get this error.

fix(TDQ-17414): fix columnset with File Connection check "Run with

---

main/plugins/org.talend.dataprofiler.top.chart/src/org/talend/dataprofiler/chart/TOPChartService.java

after changing Hide groups less than

Fix     TDQ-17182 Ubuntu: match analysis bar chart result need a click

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/MatchAnalysisDetailsPage.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/matchrule/MatchRuleMasterDetailsPage.java

Fix     TDQ-16416 the modification of MatchRule can't be saved

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/explore/FunctionFrequencyStatExplorer.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/dbms/DbmsLanguageFactory.java

fix(TDQ-17547): fix mysql Pattern frequency indicator drill down the

---

main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/migration/impl/EncryptAndDecryptPasswordTask.java
main/plugins/org.talend.dataprofiler.rcp/src/org/talend/dataprofiler/rcp/intro/Application.java

feat(TUP-21518) Remove CryptoHelper
https://jira.talendforge.org/browse/TUP-21518

feat(TUP-21518) Remove CryptoHelper

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/ColumnAnalysisSqlExecutor.java

analysis simple statistics
- revert TDQ-17316

Fix TDQ-17702 Talend Studio Data Profile (7.1.1) Discrepancy in column

---

i18n/plugins/org.talend.rcp.branding.top.nl/plugin_en.properties
i18n/plugins/org.talend.rcp.branding.top.nl/plugin_swtbot.properties
main/plugins/org.talend.dataprofiler.rcp/resources/license.txt
main/plugins/org.talend.rcp.branding.top/plugin.properties
main/plugins/org.talend.rcp.branding.top/resources/license.txt

https://jira.talendforge.org/browse/TUP-26123

bugfix(TUP-26123) Update copyright date

---

main/plugins/org.talend.dataprofiler.core/src/messages.properties
main/plugins/org.talend.dataprofiler.rcp/src/messages.properties
main/plugins/org.talend.dataprofiler.rcp/src/org/talend/dataprofiler/rcp/intro/Application.java

https://jira.talendforge.org/browse/TUP-26350

fix(TUP-26350): Add java version check for tdq

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/explore/DataExplorer.java
test/plugins/org.talend.cwm.management.test/src/org/talend/dq/analysis/explore/SimpleStatisticsExplorerTest.java

fix(TDQ-18118): fix drilldown error column reference "count" is

---

main/plugins/org.talend.dataprofiler.rcp/plugin.xml

Chore(TDQ-17695) Remove <libraryNeeded>'hadoop-core-0.20.203.0.jar'and

---

main/features/org.talend.top.feature/feature.xml
main/features/org.talend.top.libraries.feature/feature.xml

Reverts Talend/tdq-studio-se#725

Revert "TUP-27154 update feature"

---

main/features/org.talend.top.feature/feature.xml
main/features/org.talend.top.libraries.feature/feature.xml

This reverts commit 43007c17d25a3154b3a2654f62f99be2c4173c87.

Revert "chore(TDQ-18646) CVE: update beanutils to 1.9.4 (#733)"

---

main/plugins/org.talend.dataquality/META-INF/MANIFEST.MF
test/plugins/org.talend.cwm.management.test/META-INF/MANIFEST.MF

https://jira.talendforge.org/browse/TUP-27949

chore(TUP-27949): Replace log4j by slf4j

---

test/plugins/org.talend.dataprofiler.core.test/src/org/talend/dataprofiler/core/ui/utils/ModelElementIndicatorRuleTest.java

ValidPhoneForRegionCountIndicator

feat(TDQ-18439) Make junit work after add

---

main/plugins/org.talend.cwm.compare/java/src/org/talend/cwm/compare/DQStructureComparer.java
main/plugins/org.talend.cwm.compare/java/src/org/talend/cwm/compare/factory/comparisonlevel/CatalogSchemaComparisonLevel.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/cwm/management/i18n/messages.properties
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/helper/RepositoryNodeHelper.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/indicators/AbstractSchemaEvaluator.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBCalculationViewFolderRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBCalculationViewRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBConnectionRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBHDBSchemaRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBSchemaRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBTableFolderRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/DBTableRepNode.java
main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/nodes/factory/DQRepNodeCreateFactory.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/editor/analysis/OverviewResultPage.java

* feat(TDQ-19005): support calculation veiw on the SAPHana database
* feat(TDQ-19005): Support SAP Hana calculation views on DQ profiling in
Studio
* feat(TDQ-19005): update message
* feat(TDQ-19005): make sure reload work well on the calculation view
folder level and column folder level of calculation view

Zshen/feat/tdq 19005 implement calculation view (#807)

---

main/features/org.talend.top.feature/feature.xml

Reverts Talend/tdq-studio-se#817

Revert "fix(TDQ-19045) Update Jackson Databind to 2.11.4"

---

main/features/org.talend.top.feature/feature.xml

Reverts Talend/tdq-studio-se#821

Revert "Revert "fix(TDQ-19045) Update Jackson Databind to 2.11.4""

---

README.md
i18n/plugins/org.talend.rcp.branding.top.nl/plugin_en.properties
i18n/plugins/org.talend.rcp.branding.top.nl/plugin_swtbot.properties
main/plugins/org.talend.dataprofiler.core/schema/service.exsd
main/plugins/org.talend.dataprofiler.rcp/resources/license.txt
main/plugins/org.talend.dataprofiler.top.chart/script/DeployToTalendUpdate.sh
main/plugins/org.talend.rcp.branding.top/plugin.properties
main/plugins/org.talend.rcp.branding.top/resources/NOTICE.txt
main/plugins/org.talend.rcp.branding.top/resources/license.txt

https://jira.talendforge.org/browse/TUP-30114

feat(TUP-30114) update copyright.

---

main/plugins/org.talend.dataquality.standardization.migration/META-INF/MANIFEST.MF
main/plugins/org.talend.dataquality.standardization.migration/src/org/talend/dataquality/standardization/migration/FirstNameIndexMigrator.java
main/plugins/org.talend.dataquality.standardization.migration/src/org/talend/dataquality/standardization/migration/IndexMigrator.java

Reverts Talend/tdq-studio-se#853

Revert "fix(TDQ-19439) remove lucene4 from studio"

---

main/plugins/org.talend.cwm.management/src/main/java/org/talend/dq/analysis/explore/TextStatisticsExplorer.java
main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/utils/DrillDownUtils.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/FrequencyIndicatorImpl.java
main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/impl/IndicatorImpl.java

when using a delimited file with Language Japanese

fix(TDQ-19545): Cannot view rows for Maximal Length in Analysis Results

---

main/plugins/org.talend.dataquality/src/org/talend/dataquality/indicators/mapdb/TalendSerializerBase.java
test/plugins/org.talend.dataquality.test/src/org/talend/dataquality/indicators/mapdb/TalendSerializerBaseTest.java

localDateTime mapping one Long.

fix(TDQ-21546): modify Serializer and Deserializer to make sure one

---

main/plugins/org.talend.dataprofiler.rcp/src/messages.properties
main/plugins/org.talend.dataprofiler.rcp/src/org/talend/dataprofiler/rcp/intro/Application.java

https://jira.talendforge.org/browse/TUP-40916

chore(TUP-40916): Studio issues if Java version is > Java 17

---

main/plugins/org.talend.dataprofiler.rcp/src/messages.properties
main/plugins/org.talend.dataprofiler.rcp/src/org/talend/dataprofiler/rcp/intro/Application.java

https://jira.talendforge.org/browse/TUP-40916

chore(TUP-40916): Studio issues if Java version is > Java 17 
